import { Injectable } from '@nestjs/common';
import { InvoiceDocument } from './invoice-document.builder';

@Injectable()
export class InvoiceHtmlRenderer {
  render(invoice: InvoiceDocument): string {
    const itemsRows = invoice.items
      .map(
        (item) => `
        <tr>
          <td>${this.escape(item.title)}</td>
          <td>${item.quantity}</td>
          <td>$${item.unitPrice.toFixed(2)}</td>
          <td>$${item.lineSubtotal.toFixed(2)}</td>
          <td>$${item.taxAmount.toFixed(2)}</td>
          <td>$${item.lineTotal.toFixed(2)}</td>
        </tr>
      `,
      )
      .join('');

    return `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>Invoice ${invoice.invoiceNumber}</title>
<style>
  body {
    font-family: Arial, sans-serif;
    padding: 32px;
    color: #111;
  }

  .header {
    display: flex;
    justify-content: space-between;
    margin-bottom: 40px;
  }

  .brand {
    font-size: 20px;
    font-weight: bold;
  }

  .meta {
    text-align: right;
    font-size: 14px;
  }

  .section {
    margin-bottom: 24px;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 16px;
  }

  th, td {
    border-bottom: 1px solid #ddd;
    padding: 10px;
    text-align: left;
    font-size: 14px;
  }

  th {
    background: #f7f7f7;
  }

  .totals {
    margin-top: 24px;
    text-align: right;
  }

  .totals div {
    margin: 4px 0;
  }

  .total {
    font-weight: bold;
    font-size: 16px;
  }

  .footer {
    margin-top: 60px;
    font-size: 12px;
    color: #666;
  }
</style>
</head>

<body>

<div class="header">
  <div class="brand">ORCHESTRATE</div>
  <div class="meta">
    <div><strong>Invoice:</strong> ${this.escape(invoice.invoiceNumber)}</div>
    <div><strong>Status:</strong> ${this.escape(invoice.status)}</div>
    <div><strong>Issued:</strong> ${this.formatDate(invoice.issuedAt)}</div>
    <div><strong>Due:</strong> ${this.formatDate(invoice.dueAt)}</div>
  </div>
</div>

<div class="section">
  <strong>Organization:</strong> ${this.escape(invoice.organizationId)}<br/>
  <strong>Client:</strong> ${this.escape(invoice.clientId)}
</div>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Qty</th>
      <th>Unit</th>
      <th>Subtotal</th>
      <th>Tax</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    ${itemsRows}
  </tbody>
</table>

<div class="totals">
  <div>Subtotal: $${invoice.totals.subtotal.toFixed(2)}</div>
  <div>Tax: $${invoice.totals.taxTotal.toFixed(2)}</div>
  <div class="total">Total: $${invoice.totals.total.toFixed(2)}</div>
</div>

<div class="footer">
  This invoice was generated by Orchestrate.
</div>

</body>
</html>
`;
  }

  private formatDate(date: Date | null): string {
    if (!date) return '-';
    return date.toISOString().split('T')[0];
  }

  private escape(value: string): string {
    return value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }
}